### ISSUE TITLE
Search results fall behind map on places tab

### ISSUE THREAD

**Issue by theonlyjajohn** [nicolelee1012/TeamVirgil#29]
![Screenshot 2024-05-22 at 10 48 24 AM](https://github.com/nicolelee1012/TeamVirgil/assets/56231536/c74ff8a9-0bd3-4103-9ce4-35d9bb535f6f)

**Comment by nicolelee1012** [comment]
Resolved with this commit: https://github.com/nicolelee1012/TeamVirgil/commit/e66f6ab276b921b6e8dc5dda7bc5fabd8ebc2966
